### ISSUE TITLE
Clearly Identify Sections and Meta

### ISSUE THREAD

**Issue by MoonTahoe** [MoonHighway/timesplitter#51]
Coming across parent sections in the timespliter is confusing. We need a way to present these sections as dividers so the instructor clearly knows that a new section or topic is coming up. Let's blow out the old template and make these sections more like cover pages.

- [ ] (Cover) Design for Sections
  - [ ] Outline what is covered in the upcoming section
  - [ ] Add ability to display meta content if needed
- [ ] (Cover) Design for exercises
- [ ] (Cover) Design for labs
